<ul id="custom-menu">
	<li>
		<a href="#">Item 1</a>
		<ul>
			<li><a href="#">Item 1</a></li>
			<li><a href="#">Item 2</a></li>
			<li><a href="#">Item 3</a></li>
			<li><a href="#">Item 4</a></li>
			<li><a href="#">Item 5</a></li>
		</ul>
	</li>
	<li>
		<a href="#">Item 2</a>
		<ul>
			<li><a href="#">Item 1</a></li>
			<li><a href="#">Item 2</a></li>
		</ul>
	</li>
	<li>
		<a href="#">Item 2</a>
	</li>
</ul>

<style>
	#custom-menu{
		padding-left:0;
	}

	#custom-menu li{
		list-style-type: none;
		padding-left:0;
	}

	#custom-menu > li{
		display:inline-block;
	}

	#custom-menu > li > ul{
		position:absolute;
		top:100%;
		left:0;
		padding-left:0;
	}
</style>
<script>
	require(['jquery','mage/menu'],function($){
		$('#custom-menu').menu()
	})
</script>